// <auto-generated />
namespace _72HourProj.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class commentdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commentdb));
        
        string IMigrationMetadata.Id
        {
            get { return "202201262254297_commentdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
